name: AT
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
